import request from './request'

export const login = (data) => request.post('/login', data)
export const getProfile = () => request.get('/profile')
export const changePassword = (data) => request.put('/password', data)
export const updateProfileBinding = (data) => request.put('/profile/binding', data)
export const uploadImageFile = (formData) => request.post('/upload/image', formData, { headers: { 'Content-Type': 'multipart/form-data' } })
export const uploadVideoFile = (formData) => request.post('/upload/video', formData, { headers: { 'Content-Type': 'multipart/form-data' } })
export const uploadDocFile = (formData) => request.post('/upload/doc', formData, { headers: { 'Content-Type': 'multipart/form-data' } })

export const getNavList = () => request.get('/nav')
export const getNavById = (id) => request.get(`/nav/${id}`)
export const createNav = (data) => request.post('/nav', data)
export const updateNav = (id, data) => request.put(`/nav/${id}`, data)
export const deleteNav = (id) => request.delete(`/nav/${id}`)
export const reorderNav = (data) => request.put('/nav/reorder', data)

export const getPageList = (params) => request.get('/pages', { params })
export const getPageById = (id) => request.get(`/pages/${id}`)
export const createPage = (data) => request.post('/pages', data)
export const updatePage = (id, data) => request.put(`/pages/${id}`, data)
export const deletePage = (id) => request.delete(`/pages/${id}`)

export const getProductCategories = () => request.get('/product-categories')
export const getProductCategoryById = (id) => request.get(`/product-categories/${id}`)
export const createProductCategory = (data) => request.post('/product-categories', data)
export const updateProductCategory = (id, data) => request.put(`/product-categories/${id}`, data)
export const deleteProductCategory = (id) => request.delete(`/product-categories/${id}`)
export const reorderProductCategories = (data) => request.put('/product-categories/reorder', data)
export const getProductFilterTags = () => request.get('/product-filter-tags')
export const createProductFilterGroup = (data) => request.post('/product-filter-groups', data)
export const updateProductFilterGroup = (id, data) => request.put(`/product-filter-groups/${id}`, data)
export const deleteProductFilterGroup = (id) => request.delete(`/product-filter-groups/${id}`)
export const reorderProductFilterGroups = (data) => request.put('/product-filter-groups/reorder', data)
export const createProductFilterTag = (data) => request.post('/product-filter-tags', data)
export const updateProductFilterTag = (id, data) => request.put(`/product-filter-tags/${id}`, data)
export const deleteProductFilterTag = (id) => request.delete(`/product-filter-tags/${id}`)
export const reorderProductFilterTags = (tagGroup, data) => request.put(`/product-filter-tags/reorder/${tagGroup}`, data)

export const getProductList = (params) => request.get('/products', { params })
export const getProductById = (id) => request.get(`/products/${id}`)
export const searchProductByCode = (productCode) => request.get('/products/search-by-code', { params: { productCode } })
export const createProduct = (data) => request.post('/products', data)
export const updateProduct = (id, data) => request.put(`/products/${id}`, data)
export const deleteProduct = (id) => request.delete(`/products/${id}`)
export const reorderProducts = (data) => request.put('/products/reorder', data)
export const getProductFilterStatsAdmin = (params) => request.get('/products/filter-stats', { params })

// 服务管理（独立数据）
export const getServiceCategories = () => request.get('/service-categories')
export const getServiceCategoryById = (id) => request.get(`/service-categories/${id}`)
export const createServiceCategory = (data) => request.post('/service-categories', data)
export const updateServiceCategory = (id, data) => request.put(`/service-categories/${id}`, data)
export const deleteServiceCategory = (id) => request.delete(`/service-categories/${id}`)
export const reorderServiceCategories = (data) => request.put('/service-categories/reorder', data)
export const getServiceFilterTags = () => request.get('/service-filter-tags')
export const createServiceFilterGroup = (data) => request.post('/service-filter-groups', data)
export const updateServiceFilterGroup = (id, data) => request.put(`/service-filter-groups/${id}`, data)
export const deleteServiceFilterGroup = (id) => request.delete(`/service-filter-groups/${id}`)
export const reorderServiceFilterGroups = (data) => request.put('/service-filter-groups/reorder', data)
export const createServiceFilterTag = (data) => request.post('/service-filter-tags', data)
export const updateServiceFilterTag = (id, data) => request.put(`/service-filter-tags/${id}`, data)
export const deleteServiceFilterTag = (id) => request.delete(`/service-filter-tags/${id}`)
export const reorderServiceFilterTags = (tagGroup, data) => request.put(`/service-filter-tags/reorder/${tagGroup}`, data)
export const getServiceList = (params) => request.get('/services', { params })
export const getServiceById = (id) => request.get(`/services/${id}`)
export const createService = (data) => request.post('/services', data)
export const updateService = (id, data) => request.put(`/services/${id}`, data)
export const deleteService = (id) => request.delete(`/services/${id}`)
export const reorderServices = (data) => request.put('/services/reorder', data)
export const getServiceFilterStatsAdmin = (params) => request.get('/services/filter-stats', { params })

export const getNewsCategories = () => request.get('/news-categories')
export const getNewsCategoryById = (id) => request.get(`/news-categories/${id}`)
export const createNewsCategory = (data) => request.post('/news-categories', data)
export const updateNewsCategory = (id, data) => request.put(`/news-categories/${id}`, data)
export const deleteNewsCategory = (id) => request.delete(`/news-categories/${id}`)
export const reorderNewsCategories = (data) => request.put('/news-categories/reorder', data)

export const getNewsList = (params) => request.get('/news', { params })
export const getNewsById = (id) => request.get(`/news/${id}`)
export const createNews = (data) => request.post('/news', data)
export const updateNews = (id, data) => request.put(`/news/${id}`, data)
export const deleteNews = (id) => request.delete(`/news/${id}`)
export const reorderNews = (data) => request.put('/news/reorder', data)

export const getApplicationList = (params) => request.get('/applications', { params })
export const getApplicationById = (id) => request.get(`/applications/${id}`)
export const createApplication = (data) => request.post('/applications', data)
export const updateApplication = (id, data) => request.put(`/applications/${id}`, data)
export const deleteApplication = (id) => request.delete(`/applications/${id}`)

export const getInquiryList = (params) => request.get('/inquiries', { params })
export const getInquiryById = (id) => request.get(`/inquiries/${id}`)
export const handleInquiry = (id, data) => request.put(`/inquiries/${id}/handle`, data)
export const deleteInquiry = (id) => request.delete(`/inquiries/${id}`)
export const getInquiryNotifyEmails = () => request.get('/inquiries/notify-emails')
export const saveInquiryNotifyEmails = (data) => request.put('/inquiries/notify-emails', data)

export const getConfigList = () => request.get('/config')
export const upsertConfig = (data) => request.post('/config', data)
export const updateConfig = (id, data) => request.put(`/config/${id}`, data)

// 官网中心（运营可读）
export const getSiteCenter = () => request.get('/site-center')
export const saveSiteCenter = (data) => request.put('/site-center', data)

// SEO 管理
export const getSeoGlobal = () => request.get('/seo/global')
export const saveSeoGlobal = (data) => request.put('/seo/global', data)
export const getSeoPages = () => request.get('/seo/pages')
export const saveSeoPage = (id, data) => request.put(`/seo/pages/${id}`, data)
export const getSeoProducts = (params) => request.get('/seo/products', { params })
export const saveSeoProduct = (id, data) => request.put(`/seo/products/${id}`, data)
export const getSeoNews = (params) => request.get('/seo/news', { params })
export const saveSeoNews = (id, data) => request.put(`/seo/news/${id}`, data)

// 导航&底部配置
export const getFooterBlocks = () => request.get('/footer-blocks')
export const createFooterBlock = (data) => request.post('/footer-blocks', data)
export const updateFooterBlock = (id, data) => request.put(`/footer-blocks/${id}`, data)
export const deleteFooterBlock = (id) => request.delete(`/footer-blocks/${id}`)

// 页面模块化编辑
export const getPageTemplates = (pageKey) => request.get(`/page-modules/${pageKey}/templates`)
export const getPageModules = (pageKey, params) => request.get(`/page-modules/${pageKey}`, { params })
export const createPageModule = (pageKey, data) => request.post(`/page-modules/${pageKey}`, data)
export const reorderPageModules = (pageKey, data) => request.put(`/page-modules/${pageKey}/reorder`, data)
export const updatePageModule = (id, data) => request.put(`/page-module/${id}`, data)
export const deletePageModule = (id) => request.delete(`/page-module/${id}`)
export const getModuleRecycle = (params) => request.get('/module-recycle', { params })
export const reorderRecycleModules = (pageKey, data) => request.put(`/module-recycle/${pageKey}/reorder`, data)
export const restoreModuleRecycle = (id) => request.put(`/module-recycle/${id}/restore`)
export const purgeModuleRecycle = (id) => request.delete(`/module-recycle/${id}`)
export const getEditablePages = (params) => request.get('/pages', { params })
export const createEditablePage = (data) => request.post('/pages', data)
export const updateEditablePage = (id, data) => request.put(`/pages/${id}`, data)
export const deleteEditablePage = (id) => request.delete(`/pages/${id}`)

// 询价表单拖拽模板
export const getInquiryFormTemplate = () => request.get('/inquiry-form-template')
export const saveInquiryFormTemplate = (data) => request.put('/inquiry-form-template', data)

// 数据统计
export const getStatsDashboard = (params) => request.get('/stats/dashboard', { params })

// 询价导出
export const exportInquiries = (data) => request.post('/inquiries/export', data)
